services:
  website-backend:
    build:
      context: "."
      dockerfile: "website-backend/docker/Dockerfile"
    container_name: website-backend
    environment:
      - NO_LITESTREAM=true
      - ROOT_URL=http://localhost:80
      - ADDR=0.0.0.0:80
      - RUST_BACKTRACE=full
    ports:
      - 8081:80
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      # More detailed available ports explanation see at https://www.jaegertracing.io/docs/1.38/getting-started/#all-in-one
      - 4317:4317
      - 6831:6831/udp
      - 6832:6832/udp
      - 14250:14250
      - 14268:14268
      - 16686:16686
