run_tracing_server:
   docker run -d -p6831:6831/udp -p6832:6832/udp -p16686:16686 -p14268:14268 jaegertracing/all-in-one:latest

build: 
   cargo build --bin website-backend
build_release:
   cargo build --bin website-backend --release

run_with_tracing: 
   cargo run --bin website-backend --features tracing-jaeger
run_dev: 
   cargo run --bin website-backend 
run: 
   cargo run --bin website-backend --release

sqlx_update:
   sqlx migrate info --source "{{justfile_directory()}}/migrations" --database-url "sqlite://{{justfile_directory()}}/local/local.db" && cargo sqlx prepare --database-url "sqlite://{{justfile_directory()}}/local/local.db"
  

